// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt7PZIsEcoEbCUrxMSUZjtg0ChED0EW4g',
    appId: '1:545750832761:web:d340bfb5499c9bceb6e6a8',
    messagingSenderId: '545750832761',
    projectId: 'paloozatestapp',
    authDomain: 'paloozatestapp.firebaseapp.com',
    databaseURL: 'https://paloozatestapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paloozatestapp.appspot.com',
    measurementId: 'G-YW4BJF5LXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLpCp9Uu8fy5Bp-JA9BUmpBmyIPYtnvPc',
    appId: '1:545750832761:android:c9e7797cd41850aeb6e6a8',
    messagingSenderId: '545750832761',
    projectId: 'paloozatestapp',
    databaseURL: 'https://paloozatestapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paloozatestapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAkdl0cP-xvgjMTbgWXfQ8rbHhRLdmB5I',
    appId: '1:545750832761:ios:4f06d6c519aa89c5b6e6a8',
    messagingSenderId: '545750832761',
    projectId: 'paloozatestapp',
    databaseURL: 'https://paloozatestapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paloozatestapp.appspot.com',
    iosBundleId: 'com.example.paloozatestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAkdl0cP-xvgjMTbgWXfQ8rbHhRLdmB5I',
    appId: '1:545750832761:ios:2e3433bb195e2818b6e6a8',
    messagingSenderId: '545750832761',
    projectId: 'paloozatestapp',
    databaseURL: 'https://paloozatestapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paloozatestapp.appspot.com',
    iosBundleId: 'com.example.paloozatestapp.RunnerTests',
  );
}
